import { get, post } from './api.js';
import { qs, setNav, showMessage, statusBadge } from './common.js';

setNav('retrospectives');
const retroId = qs('retroId');
const message = document.getElementById('message');
const content = document.getElementById('analysis-content');

async function renderAnalysis(analysis) {
  if (!analysis) {
    content.innerHTML = '<p>No analysis yet. Close the retrospective, then generate baseline analysis.</p>';
    return;
  }
  content.innerHTML = `
    <p><strong>Generated by:</strong> ${analysis.generatedBy} · <strong>Feedback count:</strong> ${analysis.feedbackCount}</p>
    <h3>Themes</h3><ul>${analysis.themes.map((t) => `<li>${t.name}: ${t.summary}</li>`).join('') || '<li>None</li>'}</ul>
    <h3>Suggested actions (require human approval)</h3>
    ${analysis.suggestedActions.map((s) => `
      <div class="feedback-card">
        <strong>${s.title}</strong>
        <p>${s.reason}</p>
        <button data-sug="${s.id}">Approve as action</button>
      </div>
    `).join('') || '<p>None</p>'}
    <h3>Limitations</h3><ul>${analysis.limitations.map((l) => `<li>${l}</li>`).join('')}</ul>
  `;
  content.querySelectorAll('[data-sug]').forEach((btn) => {
    btn.addEventListener('click', async () => {
      try {
        await post(`/retrospectives/${retroId}/actions/from-suggestion/${btn.dataset.sug}`);
        showMessage(message, 'Suggestion approved as action.');
      } catch (err) {
        showMessage(message, err.message, true);
      }
    });
  });
}

document.getElementById('generate-btn').addEventListener('click', async () => {
  try {
    const analysis = await post(`/retrospectives/${retroId}/analysis/generate`);
    await renderAnalysis(analysis);
    showMessage(message, 'Baseline analysis generated.');
  } catch (err) {
    showMessage(message, err.message, true);
  }
});

async function load() {
  const retro = await get(`/retrospectives/${retroId}`);
  document.getElementById('retro-info').innerHTML = `<strong>${retro.title}</strong> — ${statusBadge(retro.status)}`;
  try {
    const analysis = await get(`/retrospectives/${retroId}/analysis`);
    await renderAnalysis(analysis);
  } catch {
    await renderAnalysis(null);
  }
}

if (!retroId) showMessage(message, 'Missing retroId', true);
else load().catch((err) => showMessage(message, err.message, true));
