import { get } from './api.js';
import { qs, setNav, showMessage, statusBadge, formatOwnerTeamIds } from './common.js';

setNav('retrospectives');
const retroId = qs('retroId');
const message = document.getElementById('message');
const content = document.getElementById('analysis-content');

function listSection(title, items, renderItem) {
  if (!items?.length) return `<h3>${title}</h3><p>None identified.</p>`;
  return `<h3>${title}</h3><ul>${items.map(renderItem).join('')}</ul>`;
}

let teamLabels = {};

async function renderAnalysis(analysis) {
  if (!analysis) {
    content.innerHTML = `
      <p>No analysis yet.</p>
      <p>Run <strong>/analyze-retro ${retroId || 'RETRO-YYYY-NNN'}</strong> in Cursor chat to generate AI analysis from local feedback files.</p>
    `;
    return;
  }

  const isCursor = String(analysis.generatedBy || '').includes('cursor');
  content.innerHTML = `
    <p>
      <strong>Generated by:</strong> ${analysis.generatedBy}
      ${isCursor ? '(Cursor agent)' : ''} ·
      <strong>Feedback count:</strong> ${analysis.feedbackCount}
    </p>
    ${listSection(
      'Themes',
      analysis.themes,
      (t) => `<li><strong>${t.name}</strong> [${t.feedbackIds.join(', ')}]: ${t.summary}</li>`
    )}
    ${listSection(
      'Strengths',
      analysis.strengths,
      (s) => `<li>(${s.feedbackId}) ${s.summary}</li>`
    )}
    ${listSection(
      'Concerns',
      analysis.concerns,
      (c) => `<li>(${c.feedbackId}) ${c.summary}</li>`
    )}
    ${listSection(
      'Improvement opportunities',
      analysis.opportunities,
      (o) => `<li>(${o.feedbackId}) ${o.summary}</li>`
    )}
    <h3>Suggested actions (require human approval)</h3>
    ${
      analysis.suggestedActions?.length
        ? analysis.suggestedActions
            .map(
              (s) => `
      <div class="feedback-card">
        <strong>${s.title}</strong>
        <p>${s.reason}</p>
        <p><small>Teams: ${formatOwnerTeamIds(s.ownerTeams, teamLabels)}</small></p>
        <p><small>Evidence: ${s.sourceFeedbackIds.join(', ')}</small></p>
      </div>
    `
            )
            .join('')
        : '<p>None</p>'
    }
    <h3>Limitations</h3>
    <ul>${analysis.limitations.map((l) => `<li>${l}</li>`).join('')}</ul>
  `;
}

async function load() {
  try {
    const teamsDoc = await get('/action-teams');
    teamLabels = Object.fromEntries(teamsDoc.teams.map((team) => [team.id, team.label]));
  } catch {
    teamLabels = {};
  }
  const retro = await get(`/retrospectives/${retroId}`);
  document.getElementById('retro-info').innerHTML =
    `<strong>${retro.title}</strong> — ${statusBadge(retro.status)}`;
  try {
    const analysis = await get(`/retrospectives/${retroId}/analysis`);
    await renderAnalysis(analysis);
  } catch {
    await renderAnalysis(null);
  }
}

if (!retroId) showMessage(message, 'Missing retroId', true);
else load().catch((err) => showMessage(message, err.message, true));
